### PR TITLE
1_two_sum

### PR DESCRIPTION
**Pull request by Amoonguses1**
Please check my code

### CODE REVIEW

**Comment by Amoonguses1** [comment]
I rewrote this code with binary search. But I couldn't come up with the solution whose time complexity is less than O(N). Are there more effective ways using binary search?

**Comment by Amoonguses1** [comment]
I have rewrote my code to follow Meguru style and PEP8.
@tkkawa @Ryuju0911

**Comment by tkkawa** [comment]
See [the repository](https://github.com/okuda-seminar/leetcode_answers).

**Comment by Amoonguses1** [comment]
I added hash map solution. I added error handling and docstring. Please check my code.
@tkkawa

**Review by tkkawa — APPROVED** [review]
@Amoonguses1 
LGTM

**Pull request merged**
