### PR TITLE
Add-153_find_minimum_in_rotated_sorted_array

### PR DESCRIPTION
**Pull request by Amoonguses1**
# binary search

### CODE REVIEW

**Comment by Amoonguses1** [comment]
I review this code myself. I couldn't find any more bad points. Please review my code.
@tkkawa @Ryuju0911

**Review by tkkawa — CHANGES_REQUESTED** [review]
See #8 .

**Comment by Amoonguses1** [comment]
I have fixed some parts pointed out.
@tkkawa

**Review by tkkawa — APPROVED** [review]
LGTM

**Pull request merged**
